//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTR.Viewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PTR.Viewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Directory.
        /// </summary>
        public static string String_AD {
            get {
                return ResourceManager.GetString("String_AD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AD Drive.
        /// </summary>
        public static string String_ADDrive {
            get {
                return ResourceManager.GetString("String_ADDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AD Folder.
        /// </summary>
        public static string String_ADFolder {
            get {
                return ResourceManager.GetString("String_ADFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AD Folder Accesss.
        /// </summary>
        public static string String_ADFolderAccesss {
            get {
                return ResourceManager.GetString("String_ADFolderAccesss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AD User.
        /// </summary>
        public static string String_ADUser {
            get {
                return ResourceManager.GetString("String_ADUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function [{0}].
        /// </summary>
        public static string String_Function {
            get {
                return ResourceManager.GetString("String_Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I Function.
        /// </summary>
        public static string String_IFunction {
            get {
                return ResourceManager.GetString("String_IFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I Function Access.
        /// </summary>
        public static string String_IFunctionAccess {
            get {
                return ResourceManager.GetString("String_IFunctionAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Report.
        /// </summary>
        public static string String_ImportReport {
            get {
                return ResourceManager.GetString("String_ImportReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I Quest.
        /// </summary>
        public static string String_IQuest {
            get {
                return ResourceManager.GetString("String_IQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I Quest Access.
        /// </summary>
        public static string String_IQuestAccess {
            get {
                return ResourceManager.GetString("String_IQuestAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISDAVS.
        /// </summary>
        public static string String_ISDAVS {
            get {
                return ResourceManager.GetString("String_ISDAVS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISDAVS User.
        /// </summary>
        public static string String_ISDAVSUser {
            get {
                return ResourceManager.GetString("String_ISDAVSUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession: {0}.
        /// </summary>
        public static string String_Profession {
            get {
                return ResourceManager.GetString("String_Profession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PV.
        /// </summary>
        public static string String_PV {
            get {
                return ResourceManager.GetString("String_PV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PV Emploee.
        /// </summary>
        public static string String_PVEmploee {
            get {
                return ResourceManager.GetString("String_PVEmploee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PV Hist Emploee.
        /// </summary>
        public static string String_PVHistEmploee {
            get {
                return ResourceManager.GetString("String_PVHistEmploee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PV Profession.
        /// </summary>
        public static string String_PVProfession {
            get {
                return ResourceManager.GetString("String_PVProfession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PV Structural.
        /// </summary>
        public static string String_PVStructural {
            get {
                return ResourceManager.GetString("String_PVStructural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest.
        /// </summary>
        public static string String_Quest {
            get {
                return ResourceManager.GetString("String_Quest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start typing to filter....
        /// </summary>
        public static string String_SearchPlaceholder {
            get {
                return ResourceManager.GetString("String_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status {0}.
        /// </summary>
        public static string String_Status {
            get {
                return ResourceManager.GetString("String_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PTR.
        /// </summary>
        public static string String_Title {
            get {
                return ResourceManager.GetString("String_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UUser.
        /// </summary>
        public static string String_UUser {
            get {
                return ResourceManager.GetString("String_UUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
