//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTR.PTRLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADFolderAccess
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ADFolderAccess()
        {
            this.SubFolderAccesses = new HashSet<ADFolderAccess>();
    		OnCreated();
        }
    	
    	partial void OnCreated();
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public int FolderID { get; set; }
        public Nullable<int> FileSystemRights_ { get; set; }
        public Nullable<System.DateTime> From { get; set; }
        public Nullable<System.DateTime> To { get; set; }
        public Nullable<int> ParentFolderAccessId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADFolderAccess> SubFolderAccesses { get; set; }
        public virtual ADFolderAccess ParentFolderAccess { get; set; }
        public virtual ADFolder ADFolder { get; set; }
        public virtual ADUser ADUser { get; set; }
    }
}
