//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTR.PTRLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADFolder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ADFolder()
        {
            this.ADFolderAccesses = new HashSet<ADFolderAccess>();
            this.SubFolders = new HashSet<ADFolder>();
    		OnCreated();
        }
    	
    	partial void OnCreated();
    
        public int Id { get; set; }
        public Nullable<int> ParentFolderId { get; set; }
        public int DriveId { get; set; }
        public string FullPath { get; set; }
        public bool Status { get; set; }
        public string Name { get; set; }
        public string SubHash { get; set; }
        public bool IsRootFolder { get; set; }
    
        public virtual ADDrive ADDrive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADFolderAccess> ADFolderAccesses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADFolder> SubFolders { get; set; }
        public virtual ADFolder ParentFolder { get; set; }
    }
}
