//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTR.PTRLib
{
    using System;
    
    public partial class GetGroupedPVStructurals1_Result1
    {
        public string DId { get; set; }
        public string DName { get; set; }
        public string PId { get; set; }
        public string PName { get; set; }
    }
}
