//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTR.PTRLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportReport
    {
        public int Id { get; set; }
        public int NewRecord { get; set; }
        public string Table { get; set; }
        public int RecordId { get; set; }
        public int Hide { get; set; }
    }
}
