//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTR.PTRLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class IQuestAccess
    {
        public int Id { get; set; }
        public int FunctionAccessId { get; set; }
        public int QuestId { get; set; }
        public Nullable<System.DateTime> From { get; set; }
        public Nullable<System.DateTime> To { get; set; }
    
        public virtual IFunctionAccess IFunctionAccess { get; set; }
        public virtual IQuest IQuest { get; set; }
    }
}
