//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTR.PTRLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class IQuest_import
    {
        public int quest_id { get; set; }
        public string name { get; set; }
        public string name_eng { get; set; }
        public string q_index { get; set; }
    }
}
