//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTR.PTRLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISDAVSUser_import
    {
        public int user_id { get; set; }
        public string user_login_name { get; set; }
        public string user_surname { get; set; }
        public string user_phone { get; set; }
        public string user_email { get; set; }
        public Nullable<int> user_horizon_id { get; set; }
        public string user_name { get; set; }
    }
}
