//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTR.PTRLib
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PTRContext : DbContext
    {
        public PTRContext()
            : base("metadata=res://*/PTREDM.csdl|res://*/PTREDM.ssdl|res://*/PTREDM.msl;provider=System.Data.SqlClient;provider connection string='Data Source=ALPHA\\ALPHA;Initial Catalog=ptr;Persist Security Info=True; MultipleActiveResultSets=true; User ID=PTR_generic;Password=AGXM97mm)a'")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADDrive> ADDrives { get; set; }
        public virtual DbSet<ADFolderAccess> ADFolderAccesses { get; set; }
        public virtual DbSet<ADFolder> ADFolders { get; set; }
        public virtual DbSet<ADUser> ADUsers { get; set; }
        public virtual DbSet<IFunction_import> IFunction_import { get; set; }
        public virtual DbSet<IFunctionAccess_import> IFunctionAccess_import { get; set; }
        public virtual DbSet<IFunctionAccess> IFunctionAccesses { get; set; }
        public virtual DbSet<IFunction> IFunctions { get; set; }
        public virtual DbSet<ImportReport> ImportReports { get; set; }
        public virtual DbSet<IQuest_import> IQuest_import { get; set; }
        public virtual DbSet<IQuestAccess_import> IQuestAccess_import { get; set; }
        public virtual DbSet<IQuestAccess> IQuestAccesses { get; set; }
        public virtual DbSet<IQuest> IQuests { get; set; }
        public virtual DbSet<ISDAVSUser_import> ISDAVSUser_import { get; set; }
        public virtual DbSet<ISDAVSUser> ISDAVSUsers { get; set; }
        public virtual DbSet<PVEmploee_import> PVEmploee_import { get; set; }
        public virtual DbSet<PVEmploee> PVEmploees { get; set; }
        public virtual DbSet<PVHistEmploee> PVHistEmploees { get; set; }
        public virtual DbSet<PVProfession> PVProfessions { get; set; }
        public virtual DbSet<PVStructural_import> PVStructural_import { get; set; }
        public virtual DbSet<PVStructural> PVStructurals { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UUser> UUsers { get; set; }
    
        public virtual ObjectResult<GetGroupedPVStructurals1_Result1> GetGroupedPVStructurals()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetGroupedPVStructurals1_Result1>("GetGroupedPVStructurals");
        }
    
        public virtual int UpdateAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateAll");
        }
    }
}
