//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTR.PTRLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class PVEmploee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PVEmploee()
        {
            this.Status = false;
            this.PVHistEmploees = new HashSet<PVHistEmploee>();
    		OnCreated();
        }
    	
    	partial void OnCreated();
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string NormalizedFullName { get; set; }
        public Nullable<System.DateTime> From { get; set; }
        public Nullable<System.DateTime> To { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string LocalPhone { get; set; }
        public bool Status { get; set; }
        public string DepartmentId { get; set; }
        public string PartId { get; set; }
        public Nullable<int> ProfessionId { get; set; }
        public Nullable<int> UUserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PVHistEmploee> PVHistEmploees { get; set; }
        public virtual PVProfession PVProfession { get; set; }
        public virtual UUser UUser { get; set; }
        public virtual PVStructural Part { get; set; }
        public virtual PVStructural Department { get; set; }
    }
}
